# Generated by Django 2.1.10 on 2019-07-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190712_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
